# Kong API Gateway Configuration
# DB-less declarative configuration

_format_version: "3.0"
_transform: true

#############################################
# Services
#############################################

services:
  # User Service
  - name: user-service
    url: http://user-service:3001
    connect_timeout: 10000
    write_timeout: 60000
    read_timeout: 60000
    retries: 3
    routes:
      - name: user-auth-routes
        paths:
          - /api/v1/auth
        strip_path: false
        preserve_host: true
      - name: user-routes
        paths:
          - /api/v1/users
        strip_path: false
        preserve_host: true
      - name: address-routes
        paths:
          - /api/v1/addresses
        strip_path: false
        preserve_host: true
      - name: user-health
        paths:
          - /api/v1/users/health
        strip_path: false

  # Product Service
  - name: product-service
    url: http://product-service:3002
    connect_timeout: 10000
    write_timeout: 60000
    read_timeout: 60000
    retries: 3
    routes:
      - name: product-routes
        paths:
          - /api/v1/products
        strip_path: false
        preserve_host: true
      - name: category-routes
        paths:
          - /api/v1/categories
        strip_path: false
        preserve_host: true
      - name: banner-routes
        paths:
          - /api/v1/banners
        strip_path: false
        preserve_host: true

  # Order Service
  - name: order-service
    url: http://order-service:3003
    connect_timeout: 10000
    write_timeout: 120000
    read_timeout: 120000
    retries: 2
    routes:
      - name: order-routes
        paths:
          - /api/v1/orders
        strip_path: false
        preserve_host: true

  # Cart Service
  - name: cart-service
    url: http://cart-service:3004
    connect_timeout: 5000
    write_timeout: 30000
    read_timeout: 30000
    retries: 3
    routes:
      - name: cart-routes
        paths:
          - /api/v1/cart
        strip_path: false
        preserve_host: true

  # Notification Service
  - name: notification-service
    url: http://notification-service:3005
    connect_timeout: 10000
    write_timeout: 60000
    read_timeout: 60000
    retries: 2
    routes:
      - name: notification-routes
        paths:
          - /api/v1/notifications
        strip_path: false
        preserve_host: true

#############################################
# Plugins (Global)
#############################################

plugins:
  # Request/Response Logging
  - name: file-log
    config:
      path: /dev/stdout
      reopen: true

  # Request ID
  - name: correlation-id
    config:
      header_name: X-Request-ID
      generator: uuid
      echo_downstream: true

  # CORS
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Authorization
        - Content-Type
        - X-Request-ID
        - X-Idempotency-Key
      exposed_headers:
        - X-Request-ID
        - X-RateLimit-Limit-Second
        - X-RateLimit-Remaining-Second
      credentials: true
      max_age: 3600

  # Rate Limiting (Global)
  - name: rate-limiting
    config:
      second: 100
      minute: 1000
      policy: redis
      redis_host: redis
      redis_port: 6379
      fault_tolerant: true
      hide_client_headers: false

  # Request Size Limiting
  - name: request-size-limiting
    config:
      allowed_payload_size: 10
      size_unit: megabytes

  # Security Headers
  - name: response-transformer
    config:
      add:
        headers:
          - "X-Content-Type-Options: nosniff"
          - "X-Frame-Options: DENY"
          - "X-XSS-Protection: 1; mode=block"
          - "Strict-Transport-Security: max-age=31536000; includeSubDomains"

#############################################
# Consumers
#############################################

consumers:
  - username: mobile-app
    custom_id: vurksha-mobile-app

#############################################
# Upstreams (for load balancing)
#############################################

upstreams:
  - name: user-service-upstream
    slots: 10000
    healthchecks:
      active:
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          http_failures: 3
          interval: 5
        http_path: /health/live
        timeout: 5
        type: http
      passive:
        healthy:
          successes: 3
        unhealthy:
          http_failures: 3
    targets:
      - target: user-service:3001
        weight: 100

  - name: product-service-upstream
    slots: 10000
    healthchecks:
      active:
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          http_failures: 3
          interval: 5
        http_path: /health/live
        timeout: 5
        type: http
      passive:
        healthy:
          successes: 3
        unhealthy:
          http_failures: 3
    targets:
      - target: product-service:3002
        weight: 100

  - name: order-service-upstream
    slots: 10000
    healthchecks:
      active:
        healthy:
          interval: 5
          successes: 2
        unhealthy:
          http_failures: 3
          interval: 5
        http_path: /health/live
        timeout: 5
        type: http
      passive:
        healthy:
          successes: 3
        unhealthy:
          http_failures: 3
    targets:
      - target: order-service:3003
        weight: 100
